### ISSUE TITLE
WebPKIError(CertNotValidForName)

### ISSUE THREAD

**Issue by GopherJ** [ctz/rustls#322]
I'm trying to make `rumqtt` works with tls, it depends on `rustls`, but after one week I still cannot make a simple example work, always different kinds of tls error.

I wrote a script which generates a SAN certificate.

```bash
#!/bin/bash

set -e
set -u

HOST=emqtt.ubudu.com
SUBJ_ROOT="/C=FR/ST=Paris/O=EMQ/CN=Ubudu"
SUBJ_CLIENT="/C=FR/ST=Paris/O=EMQ/CN=Client"
SUBJ_SERVER="/C=FR/ST=Paris/O=EMQ/CN=Server"
DAYS=3650

openssl genrsa -out root-ca.key 2048

openssl req \
  -x509 \
  -nodes \
  -new \
  -key root-ca.key \
  -out root-cacert.pem \
  -subj $SUBJ_ROOT \
  -sha256 \
  -days $DAYS

(cat /etc/ssl/openssl.cnf; printf "[SAN]\nsubjectAltName=DNS:$HOST") > openssl.cnf

openssl genrsa -out client.key 2048

openssl req \
  -new \
  -key client.key \
  -out client-cert.csr \
  -subj $SUBJ_CLIENT \
  -reqexts SAN \
  -extensions SAN \
  -config openssl.cnf

openssl x509 \
  -req \
  -in client-cert.csr \
  -out client-cert.pem \
  -CA root-cacert.pem \
  -CAkey root-ca.key \
  -CAcreateserial \
  -CAserial $HOST-CA.serial \
  -extensions SAN \
  -extfile openssl.cnf \
  -sha256 \
  -days $DAYS

openssl req \
  -new \
  -key server.key \
  -out server-cert.csr\
  -subj $SUBJ_SERVER \
  -reqexts SAN \
  -extensions SAN \
  -config openssl.cnf

openssl x509 \
  -req \
  -in server-cert.csr \
  -out server-cert.pem \
  -CA root-cacert.pem \
  -CAkey root-ca.key \
  -CAcreateserial \
  -CAserial $HOST-CA.serial \
  -extensions SAN \
  -extfile openssl.cnf \
  -sha256 \
  -days $DAYS
```

error:
```
ERROR rumqtt::client::connection > Connection error = Error(Inner(Io(Custom { kind: InvalidData, error: WebPKIError(CertNotValidForName) })))
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: WebPKIError(CertNotValidForName) })', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

trace:
```
 ERROR rumqtt::client::connection > Connection error = Error(Inner(Io(Custom { kind: InvalidData, error: WebPKIError(CertNotValidForName) })))
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: WebPKIError(CertNotValidForName) })', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:933
  16: tls::main
             at examples/tls.rs:17
  17: std::rt::lang_start::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  21: std::panicking::try
             at src/libstd/panicking.rs:271
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  24: std::rt::lang_start
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ctz** [comment]
Sorry, I can't reproduce this. Here's what I did:

1. Generated a `server.key` with `openssl genrsa -out server.key 2048`
2. Ran your script to generate the rest of the certs/keys.
3. Ran `./target/debug/examples/tlsserver --certs tmp/server-cert.pem --key tmp/server.key -p 8443 http` where the output files from your script are in `tmp/`.
4. Arranged for `emqtt.ubudu.com` to resolve to 127.0.0.1
5. Ran `./target/debug/examples/tlsclient --cafile tmp/root-cacert.pem -p 8443 --http emqtt.ubudu.com`, which worked.

In the rumqtt crate, the hostname used in `examples/tls.rs` and associated certificates are localhost. This doesn't match `emqtt.ubudu.com` which will cause this error.
